FROM ubuntu:latest
MAINTAINER "snitkin.d@list.ru"
# apt-transport-https & wget
RUN apt update && \
    apt -y install apt-transport-https wget
# Unzip
RUN apt install unzip
# Java
RUN apt -y install openjdk-11-jdk xvfb
# Perl
RUN apt -y install perl
# Create /.bashrc for aliases
# Execute ". /.bashrc" command right after the container is run
RUN touch /.bashrc
# FastQC v0.11.9
RUN wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip && \
    unzip fastqc_v0.11.9.zip && \
    rm fastqc_v0.11.9.zip && \
    chmod a+x /FastQC/fastqc && \
    echo 'alias fastqc="/FastQC/fastqc"' >> /.bashrc # && \
# STAR v2.7.10b
RUN wget https://github.com/alexdobin/STAR/releases/download/2.7.10b/STAR_2.7.10b.zip && \
    unzip ./STAR_2.7.10b.zip && \
    rm ./STAR_2.7.10b.zip && \
    chmod a+x ./STAR_2.7.10b/Linux_x86_64_static/STAR ?? \
    mv ./STAR_2.7.10b/Linux_x86_64_static/STAR /bin/STAR && \
    rm -r ./STAR_2.7.10b
# samtools v1.16.1
RUN wget https://github.com/samtools/samtools/archive/refs/tags/1.16.1.zip -O ./samtools-1.16.1.zip && \
    unzip ./samtools-1.16.1.zip && \
    rm ./samtools-1.16.1.zip && \
    mv ./samtools-1.16.1/misc /samtools && \
    rm -r ./samtools-1.16.1 && \
    echo 'alias samtools="/samtools/samtools.pl"' >> /.bashrc
# picard v2.27.5
RUN wget https://github.com/broadinstitute/picard/releases/download/2.27.5/picard.jar -O /bin/picard.jar && \
    chmod a+x /bin/picard.jar && \
    echo 'alias picard="java -jar /bin/picard.jar"' >> /.bashrc
# bedrools v2.30.0
RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.30.0/bedtools.static.binary -O /bin/bedtools.static.binary && \
    chmod a+x /bin/bedtools.static.binary && \
    echo 'alias bedtools="/bin/bedtools.static.binary"' >> /.bashrc
# Python 3 with pip
RUN apt -y install python3-pip
# MultiQC v1.13
RUN pip install multiqc==1.13
# salmon v1.9.0 with libgomp1 and libtbb12 needed for its functioning
RUN wget https://github.com/COMBINE-lab/salmon/releases/download/v1.9.0/salmon-1.9.0_linux_x86_64.tar.gz && \
    tar -zxvf ./salmon-1.9.0_linux_x86_64.tar.gz && \
    rm salmon-1.9.0_linux_x86_64.tar.gz && \
    chmod a+x ./salmon-1.9.0_linux_x86_64/bin/salmon && \
    mv ./salmon-1.9.0_linux_x86_64/bin/salmon /bin/salmon && \
    rm -r ./salmon-1.9.0_linux_x86_64 && \
    apt install libgomp1 libtbb12
